@MultiTenancy_HostAddress = https://localhost:7014

GET {{MultiTenancy_HostAddress}}/api/products/{id:int}?id=0

###

POST {{MultiTenancy_HostAddress}}/api/products
Content-Type: application/json

{
  //CreateProductDto
}

###
